---
# Where the receipts are stored
# Receipts should be simple text files
receipts_path: "txt"

# Market names roughly ordered by likelyhood.
# Can contain market locations for fuzzy parsing
markets:
  Penny:
     - penny
     - p e n n y
     - m a r k t gmbh
  REWE:
     - rewe
  Real:
     - real
  Netto:
     - netto-online
  Kaiser's:
     - kaiser
     - kaiserswerther straße 270
  Aldi:
     - aldi
     - friedrichstr 128—133
  Lidl:
     - lidl
  Edeka:
    - edeka
  Drogerie:
     - drogerie
  Kodi:
     - kodi
  Getraenke:
    - Getraenke Tempel
  Tanken:
     - shell
     - esso station
     - aral
     - total tankstelle
     - RK Tankstellen
  Migros:
     - genossenschaft migros

# Sum keys roughly ordered by likelyhood.
sum_keys:
  - importo
  - importo pagato
  - totale
  - importo totale
  - euro
  - E
  - importo E
  - E importo
  - importo pagato E
  - E importo pagato
  - E totale
  - totale E
  - E importo totale
  - importo totale E
  - costo della corsa
  - costo della corsa E
  - E costo della corsa
  - tariffa predeterminata
  - E tariffa predeterminata
  - tariffa
  - ammontare

sum_format: '^\d+(\/\d{1,2}|\,\d{1,2}|\.\d{1,2})?$'
date_format: '.*?(?P<date>(\d{2,4}(\.\s?|[^a-zA-Z\d])\d{1,2}(\.\s?|[^a-zA-Z\d])(20)?1[1-9]))'

